openapi: 3.1.0
info:
  title: Alpha Trading Edge
  version: 2.0.0
servers:
  - url: https://alpaca-py-production.up.railway.app
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
paths:
  /v2/orders:
    post:
      summary: Create order
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema: { }
        '400': { description: Bad Request }
        '401': { description: Unauthorized }
        '409': { description: Price drift exceeded }
        '428': { description: Quote stale }
  /v2/orders/{order_id}:
    get:
      summary: Get order
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: order_id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { }
    delete:
      summary: Cancel order
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: order_id
          required: true
          schema: { type: string }
      responses:
        '204': { description: Cancelled }
        '404': { description: Not Found }
  /v2/watchlist:
    get:
      summary: List watchlists
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { }
    post:
      summary: Create watchlist
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
  /v2/watchlist/{id}:
    get:
      summary: Get watchlist
      security: [ { ApiKeyAuth: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses: { '200': { description: OK } }
    delete:
      summary: Delete watchlist
      security: [ { ApiKeyAuth: [] } ]
      parameters: [ { in: path, name: id, required: true, schema: { type: string } } ]
      responses: { '204': { description: Deleted } }
